# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# A sample workflow which checks out your Infrastructure as Code Configuration files,
# such as Kubernetes, Helm & Terraform and scans them for any security issues.
# The results are then uploaded to GitHub Security Code Scanning
#
# For more examples, including how to limit scans to only high-severity issues
# and fail PR checks, see https://github.com/snyk/actions/

name: Snyk Infrastructure as Code

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '27 19 * * 1'

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
      - uses: actions/checkout@v2
      - name: Run Bicep build
        uses: aliencube/bicep-build-actions@v0.3
        with:
          files: '**/*.bicep'
      - uses: snyk/actions/setup@master
      - name: Snyk Test 
        run: snyk iac test --sarif-file-output=snyk-sarif.json
        continue-on-error: true        
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}     
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk-sarif.json
          
